[package]
name = "utf8ify"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chardetng = "0.1.14"
ripgrep = "13.0.0"
encoding_rs = "0.8.28"

