# This is a cargo-make setting file.
#
# Tasks can be excuetd by:
#  cargo make [TASK_NAME]
# e.g.
#  cargo make coverage
#
# About source-based code coverage:
#  https://github.com/mozilla/grcov#example-how-to-generate-source-based-coverage-for-a-rust-project
#  https://marco-c.github.io/2020/11/24/rust-source-based-code-coverage.html
#

[tasks.llvm_install]
install_crate = { rustup_component_name = "llvm-tools-preview" }

# Extends the setting in the built-in settings file:
#  https://github.com/sagiegurari/cargo-make/blob/ee4e8b40319532079750d26c7d2415c0c6fbc306/src/lib/descriptor/makefiles/rust.toml#L387
[tasks.build-cov]
extend = "build"
env = { RUSTFLAGS="-Zinstrument-coverage" }
dependencies = ["llvm_install"]

# Extends the setting in the built-in settings file:
#  https://github.com/sagiegurari/cargo-make/blob/ee4e8b40319532079750d26c7d2415c0c6fbc306/src/lib/descriptor/makefiles/rust.toml#L411
[tasks.test-cov]
extend = "test"
env = { LLVM_PROFILE_FILE="your_name-%p-%m.profraw" }
dependencies = ["build-cov"]

# Overwrites the tasks.coverage setting in the built-in settings file:
#  https://github.com/sagiegurari/cargo-make/blob/ee4e8b40319532079750d26c7d2415c0c6fbc306/src/lib/descriptor/makefiles/rust-coverage.toml
[tasks.coverage]
clear = true
description = "Runs source-based code coverage."
category = "Test"
command = "grcov . --binary-path ./target/debug -s . -t html --branch --ignore-not-existing -o ./target/debug/coverage/"
dependencies = ["test-cov"]

